CREATE TABLE  "EMPLOYEE" 
   (	"EMPLOYEE_ID" NUMBER(6,0), 
	"FIRST_NAME" VARCHAR2(50), 
	"LAST_NAME" VARCHAR2(50), 
	"DOB" DATE, 
	"DOJ" DATE, 
	"SALARY" NUMBER(6,0), 
	"GENDER" CHAR(1), 
	"STATUS" VARCHAR2(8), 
	"EMAIL_ID" VARCHAR2(15), 
	"PHONE" NUMBER(15,0), 
	 CONSTRAINT "EMPLOYEE_ID" PRIMARY KEY ("EMPLOYEE_ID") ENABLE
   )