package com.hib.entities;

// Generated 27 Jul, 2017 1:25:18 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeAddress generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_ADDRESS", schema = "CHETHANORACLE")
public class EmployeeAddress implements java.io.Serializable {

	private int employeeAddressId;
	private Employee employee;
	private String address;
	private String city;
	private String district;
	private String state;
	private Long zipcode;
	private Integer addressTypeId;

	public EmployeeAddress() {
	}

	public EmployeeAddress(int employeeAddressId) {
		this.employeeAddressId = employeeAddressId;
	}


	@Id
	@Column(name = "EMPLOYEE_ADDRESS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getEmployeeAddressId() {
		return this.employeeAddressId;
	}

	public void setEmployeeAddressId(int employeeAddressId) {
		this.employeeAddressId = employeeAddressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "ADDRESS", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CITY", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "DISTRICT", length = 20)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "STATE", length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIPCODE", precision = 15, scale = 0)
	public Long getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Long zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "ADDRESS_TYPE_ID", precision = 5, scale = 0)
	public Integer getAddressTypeId() {
		return this.addressTypeId;
	}

	public void setAddressTypeId(Integer addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

}
